name: Build and Review on PR to main

on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Run tests
        run: npm run test-headless

  review-on-change:
    runs-on: ubuntu-latest
    needs: test-and-build
    if: ${{ github.event_name == 'pull_request' && contains(github.event.pull_request.changed_files, 'no_change/') }}

    steps:
      - name: Request review
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr_number = context.payload.pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            
            const review = await github.pulls.createReview({
              owner: owner,
              repo: repo,
              pull_number: pr_number,
              event: 'REQUEST_CHANGES',
              body: 'Changes in the "no_change" folder require review.'
            });
            console.log('Review requested:', review.data.html_url);
