name: Build and Review on PR to main
on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Run tests
        run: npm run test-headless

  request-review:
    runs-on: ubuntu-latest
    needs: test-and-build
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    
    steps:
      - name: Request review
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.payload.repository.owner.login;
            const repo = context.payload.repository.name;
            const prNumber = context.payload.pull_request.number;
            const reviewers = ['UmbrellaCrow612']; // List of reviewers

            for (const reviewer of reviewers) {
              octokit.pulls.createReviewRequest({
                owner,
                repo,
                pull_number: prNumber,
                reviewers: [reviewer],
              });
            }
