name: Request Review on Folder Changes

on:
  push:
    paths:
      - 'no_change/**' # Trigger only when there are changes in the no_change folder

jobs:
  request_review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Request review
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const changes = github.context.payload.commits.map(commit => commit.added.concat(commit.modified));

            if (changes.some(path => path.startsWith('no_change/'))) {
              const owner = github.context.payload.repository.owner.login;
              const repo = github.context.payload.repository.name;
              const pullRequestNumber = github.context.payload.pull_request.number;

              const { data: currentUser } = await github.rest.users.getAuthenticated();
              const { data: ownerUser } = await github.rest.users.getByUsername({
                username: owner
              });

              if (currentUser.login !== ownerUser.login) {
                await github.rest.pulls.createReview({
                  owner: owner,
                  repo: repo,
                  pull_number: pullRequestNumber,
                  event: 'REQUEST_REVIEW',
                  reviewers: [owner]
                });
              } else {
                console.log('Skipping review request as the pusher is the repository owner.');
              }
            } else {
              console.log('No changes in the no_change folder. Skipping review request.');
            }
