name: "Review for um"

on:
  pull_request:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Send Review Request"
        if: github.actor == 'UmbrellaCrow612'
        uses: kunihiko-t/review-request-action@v0.1.3
        with:
          repo-token: ${{ secrets.TOKEN }}
          reviewers: "UmbrellaCrow612"
          team-reviewers: "a,b,c"
