name: Request Review from umbrellaCrow612 on Folder Changes

on:
  push:
    paths:
      - 'no_change/**' # Trigger only when there are changes in the no_change folder

jobs:
  request_review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Request review
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const commits = await github.rest.pulls.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });

            const changedFiles = new Set();
            commits.data.forEach(commit => {
              commit.files.forEach(file => {
                if (file.filename.startsWith('no_change/')) {
                  changedFiles.add(file.filename);
                }
              });
            });

            if (changedFiles.size > 0) {
              const pullRequestNumber = context.payload.pull_request.number;

              await github.rest.pulls.createReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pullRequestNumber,
                event: 'REQUEST_REVIEW',
                reviewers: ['umbrellaCrow612']
              });
            } else {
              console.log('No changes in the no_change folder. Skipping review request.');
            }
