name: Require Review for no_change Modifications

on:
  pull_request:
    paths:
      - 'no_change/**' # This will trigger the workflow only if there are changes in the no_change folder

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for modifications
        id: check_modifications
        run: |
          changes=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- no_change/)
          if [ -n "$changes" ]; then
            echo "Modifications detected in no_change folder."
            echo "::set-output name=modifications::true"
          else
            echo "No modifications in no_change folder."
            echo "::set-output name=modifications::false"
          fi

      - name: Request review if necessary
        if: steps.check_modifications.outputs.modifications == 'true'
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            
            const review = await github.pulls.createReview({
              owner: owner,
              repo: repo,
              pull_number: prNumber,
              event: 'REQUEST_CHANGES',
              comments: [
                {
                  path: 'no_change/',
                  position: 1, // You might need to adjust this position
                  body: 'Modifications detected in the no_change folder. Please review.',
                },
              ],
            });
            
            console.log('Review requested:', review.data);
