name: PR Review for umbrellacrow612

on:
  pull_request:
    types:
      - opened

jobs:
  request_review:
    runs-on: ubuntu-latest
    
    steps:
      - name: Request review
        if: github.event.pull_request.user.login == 'umbrellacrow612'
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            console.log(`Requesting review from: umbrellacrow612`);
            
            const response = await github.pulls.createReviewRequest({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              reviewers: ['umbrellacrow612']
            });
            console.log(response);
