name: PR Review Workflow

on:
  pull_request:
    paths:
      - 'no-change/**'
    types:
      - opened
      - synchronize

jobs:
  pr_review:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Request review
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: reviews } = await github.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });

            const reviewRequested = reviews.some(review => review.user.login === 'umbrellaman612');

            if (!reviewRequested) {
              await github.pulls.createReviewRequest({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                reviewers: ['umbrellaman612'],
              });
            }
