name: PR Review Workflow

on:
  pull_request:
    paths:
      - 'no-change/**'
    types:
      - opened
      - synchronize

jobs:
  pr_review:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Add Pull Request Reviewer
        uses: AveryCameronUofR/add-reviewer-gh-action@1.0.4
        with:
          reviewers: "umbrellaman612"
          token: ${{ secrets.GITHUB_TOKEN }}
